package com.nqt.training.component;

import org.springframework.stereotype.Component;

@Component
public class LongMessageFormatter {

    public String format() {
        return "Long message: Hello! This is a longer formatted message generated by the service.";
    }
}