package com.project.ReimbursementPortal.entity;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Column;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Data
@Entity
@Table(name = "claim")
public class Claim {

    /** Maximum length allowed for the claim description. */
    private static final int DESCRIPTION_MAX_LENGTH = 1000;
    /** Maximum length allowed for reviewer comments. */
    private static final int REVIEWER_COMMENTS_MAX_LENGTH = 1000;

    /**
     * The unique identifier for the claim, automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The amount of money being claimed for reimbursement. This field is required and cannot be null.
     */
    @Column(nullable = false)
    private BigDecimal amount;

    /**
     * The date when the expense was incurred. This field is required and cannot be null.
     */
    @Column(nullable = false)
    private LocalDate date;

    /**
     * A detailed description of the claim, providing context and justification for the reimbursement request.
     * This field is optional and can be up to fixed length.
     */
    @Column(length = DESCRIPTION_MAX_LENGTH)
    private String description;

    /**
     * The current status of the claim, which can be one of the following: PENDING, APPROVED, or REJECTED.
     * This field is required and cannot be null.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ClaimStatus status;

    /**
     * The identifier of the employee who submitted the claim. This field is required and cannot be null.
     */
    @Column(name = "employee_id", nullable = false)
    private Long employeeId;

    /**
     * A list of identifiers for the reviewers who have evaluated the claim.
     * This field is optional and can contain multiple reviewer IDs.
     */
    @Column(name = "reviewer_id")
    private List<Long> reviewerIds;

    /**
     * Comments provided by the reviewers during the evaluation process.
     * This field is optional and can be up to fixed length.
     */
    @Column(name = "reviewer_comments", length = REVIEWER_COMMENTS_MAX_LENGTH)
    private String reviewerComments;

    /**
     * The timestamp when the claim was created.
     * This field is automatically set by the database and cannot be updated after creation.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * The timestamp when the claim was last updated.
     * This field is automatically updated by the database whenever the claim is modified.
     */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}

