package com.project.ReimbursementPortal.entity;

import com.project.ReimbursementPortal.enums.ClaimStatus;
import jakarta.persistence.Entity;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.EnumType;
import jakarta.persistence.Column;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "claims")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Claim {

    /**
     * Unique identifier for the claim.
     * This is the primary key for the claims table and is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The amount of the claim.
     */
    private Double amount;

    /**
     * The date of the expense or claim.
     * This represents when the expense occurred, not when the claim was submitted.
     */
    private LocalDate date;

    /**
     * The title of the claim, providing a brief summary of the expense.
     */
    private String title;

    /**
     * A description of the claim, providing details about the expense being claimed.
     */
    private String description;

    /**
     * The current status of the claim (e.g., SUBMITTED, APPROVED, REJECTED).
     */
    @Enumerated(EnumType.STRING)
    private ClaimStatus status;

    /**
     * The ID of the employee who submitted the claim.
     */
    @Column(name = "employee_id")
    private Long employeeId;

    /**
     * The ID of the reviewer assigned to process this claim.
     */
    @Column(name = "reviewer_id")
    private Long reviewerId;

    /**
     * Comments from the reviewer regarding the claim, such as reasons for approval or rejection.
     */
    private String comments;

    /**
     * Timestamp indicating when the claim was created.
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;


    /**
     * Timestamp indicating when the claim was last updated (e.g., when its status changes).
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = true)
    private LocalDateTime updatedAt;
}
