package com.project.ReimbursementPortal.entity;

import com.project.ReimbursementPortal.enums.UserRole;

import jakarta.persistence.Entity;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.EnumType;
import jakarta.persistence.Column;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "users")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class User {

    /**
     * Unique identifier for the user. This is the primary key for the users table and is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the user.
     * This field is required and is used for display purposes in the application.
     * It can also be used for personalization and to identify the user in various parts of the application.
     */
    private String name;

    /**
     * Email of the user. This field is required and must be unique across all users.
     */
    private String email;

    /**
     * Password of the user. This field is required and should be stored securely (e.g., hashed) in the database.
     */
    private String password;

    /**
     * Role of the user (e.g., ADMIN, EMPLOYEE). This field is required and is used for authorization purposes in the application.
     */
    @Enumerated(EnumType.STRING)
    private UserRole role;

    /**
     * Manager ID of the user. This field is relevant for employees, indicating who their manager is.
     * It can be null for users with the ADMIN role.
     */
    private Long managerId;

    /**
     * Timestamp indicating when the user was created.
     * This field is automatically set by the database when a new user record is inserted and is not updatable.
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
